name: mini_project_mandor_pc
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_speed_dial: ^6.2.0
  google_fonts: ^4.0.4
  http: ^0.13.5
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.16.10
  mockito: ^5.0.15
  build_runner: ^2.1.5

flutter:
  uses-material-design: true
